In [8]:
import numpy as np
import time

In [6]:
a = np.array([1,2,3])
print(a, a.shape)

b = np.array([[1,2,3]])
print(b, b.shape)

c = np.array([[1,2,3], [2,3,4]])
print(c, c.shape)

print(a[0], b[0], c[1][2])

[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1 2 3]
 [2 3 4]] (2, 3)
1 3 4


In [13]:
r1 = np.random.rand(100000)
r2 = np.random.rand(100000)

print(r1,r2)
print(r1.shape, r2.shape)

resultado = 0

t0 = time.time()

for i in range(100000):
  resultado += r1[i] * r2[i]
t1 = time.time()

print(resultado, (t1-t0) * 1000, "ms")

resultado = 0


t0 = time.time()

resultado = np.dot(r1,r2)
t1 = time.time()

print(resultado, (t1-t0) * 1000, "ms")

[0.62574319 0.99533153 0.22966669 ... 0.15251057 0.2363883  0.835852  ] [0.05963019 0.89025296 0.03849912 ... 0.44271915 0.29822596 0.01964265]
(100000,) (100000,)
24951.92117438902 63.78889083862305 ms
24951.92117438878 1.1124610900878906 ms


In [18]:
zeroes = np.zeros((3,3))
print(zeroes, zeroes.shape)

ones = np.ones((3,5))
print(ones , ones.shape)

#util para matriz de pesos 
randoms = np.random.random((3, 3))
print(randoms, randoms.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (3, 5)
[[0.79299969 0.93571937 0.73323464]
 [0.51467911 0.06763755 0.46134666]
 [0.57220499 0.68484634 0.3736495 ]] (3, 3)


In [ ]:
randoms = 